site_name: 晨峦的咖啡馆
theme:
  name: material
  language: zh
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.prune
  - navigation.indexes
  - toc.follow
  - navigation.top
  - search.suggest
  palette: 
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: brown
    accent: deep orange
    toggle:
      icon: material/brightness-7 
      name: 切换到深色模式
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: brown
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: 切换到浅色模式

# extra:
#   alternate:
#   - name: 简体中文
#     link: /zh/
#     lang: zh

nav:
- home: index.md
- blog: blog/index.md

plugins:
- search
- blog:
    post_date_format: medium
- i18n:
    docs_structure: suffix
    fallback_to_default: true
    reconfigure_material: true
    reconfigure_search: true
    languages:
    - locale: zh
      build: true
      default: true
      name: 简体中文
      site_name: 晨峦的咖啡馆
      nav_translations:
        home: 主页
        blog: 博客