site_name: 晨峦的咖啡馆
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
