site_name: 晨峦的咖啡馆
site_description: 欢迎光临，这里是晨峦的个人站点~
site_author: 晨峦
site_url: https://chen-luan.github.io/
repo_url: https://github.com/Chen-Luan/Chen-Luan.github.io
theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.tabs
  - navigation.prune
  - navigation.indexes
  - toc.follow
  - navigation.top
  - search.suggest
  - content.code.copy
  palette: 
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: brown
    accent: deep orange
    toggle:
      icon: material/brightness-7 
      name: 切换到深色模式
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: brown
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: 切换到浅色模式

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  # alternate:
  # - name: 简体中文
  #   link: /zh/
  #   lang: zh

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
- home: index.md
- notes: 
  - 2023:
    - dec: notes/2023/dec.md
- essay:
  - music-theory-foundation-for-charting: essay/music-theory-foundation-for-charting.md

plugins:
- search:
    separator: '[\s\u200b\-]'
- i18n:
    docs_structure: suffix
    fallback_to_default: true
    reconfigure_material: true
    reconfigure_search: true
    languages:
    - locale: zh
      build: true
      default: true
      name: 简体中文
      site_name: 晨峦的咖啡馆
      nav_translations:
        home: 主页
        notes: 便笺墙
        dec: 十二月
        essay: 札记随笔
        music-theory-foundation-for-charting: 制谱乐理基础入门 Part2