site_name: 晨峦的咖啡馆
site_description: 欢迎光临，这里是晨峦的个人站点~
site_author: 晨峦
site_url: https://chen-luan.github.io/
repo_url: https://github.com/Chen-Luan/Chen-Luan.github.io
theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.tabs
  - navigation.prune
  - navigation.indexes
  - toc.follow
  - navigation.top
  - search.suggest
  - content.code.copy
  palette: 
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: brown
    accent: deep orange
    toggle:
      icon: material/brightness-7 
      name: 切换到深色模式
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: brown
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: 切换到浅色模式

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-8M56KCQHEH
  generator: false
  # alternate:
  # - name: 简体中文
  #   link: /zh/
  #   lang: zh

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
- home: 
  - home: index.md
  - about-copyright: home/about-copyright.md
# - notes: 
#   - 2024:
#     - feb: notes/2024/feb.md
#     - jan: notes/2024/jan.md
#   - 2023:
#     - dec: notes/2023/dec.md
- essay:
  - music-theory-foundation-for-charting: essay/music-theory-foundation-for-charting.md
  - chart-creation-concepts: essay/chart-creation-concepts.md
  - concept-of-ai: essay/concept-of-ai.md
  - fast-mkdocs-personal-site: essay/fast-mkdocs-personal-site.md
#   - let-us-talk-about-game-development: essay/let-us-talk-about-game-development.md
- exhibition:
  - chart-cys-yys: exhibition/chart-cys-yys.md
  - chart-rd-afterschool: exhibition/chart-rd-afterschool.md
  - chart-rd-ddydd: exhibition/chart-rd-ddydd.md
  - chart-xzzg-demo: exhibition/chart-xzzg-demo.md
  - chart-ma-mrdisco: exhibition/chart-ma-mrdisco.md
  - chart-schi-qq: exhibition/chart-schi-qq.md

plugins:
- search:
    separator: '[\s\u200b\-]'
- i18n:
    docs_structure: suffix
    fallback_to_default: true
    reconfigure_material: true
    reconfigure_search: true
    languages:
    - locale: zh
      build: true
      default: true
      name: 简体中文
      site_name: 晨峦的咖啡馆
      nav_translations:
        home: 主页
        about-copyright: 关于网页内容版权的说明
        notes: 便笺墙
        dec: 十二月
        feb: 二月
        jan: 一月
        essay: 札记随笔
        music-theory-foundation-for-charting: 制谱乐理基础入门
        chart-creation-concepts: 谱面创作理念
        concept-of-ai: 关于 AI 的个人理念
        let-us-talk-about-game-development: 让我们来聊聊游戏开发吧
        fast-mkdocs-personal-site: 从零开始快速搭建个人网页
        exhibition: 展览橱窗
        chart-cys-yys: CyS 官谱 《云与诗》
        chart-rd-afterschool: RD 自制谱《After School》
        chart-rd-ddydd: RD 自制谱《呆呆一呆呆》(ShortVer)
        chart-xzzg-demo: 协奏之歌 官谱演示
        chart-ma-mrdisco: Ma 自制谱 《末日DISCO》
        chart-schi-qq: Schi 自制谱 《鹊桥》
